### ISSUE TITLE
Failed to load the plugin "installer_omod.dll"

### ISSUE THREAD

**Issue by nabel0** [Ashok0/HL2VREssentials#2] opened 2022-09-18 11:31 UTC
Getting this error whan i start the Mod Organizer..
If i skip it it seems to works...

![Screenshot 2022-09-18 132734](https://user-images.githubusercontent.com/50377455/190899882-d1eecf00-d108-4c3b-80c4-e4afb5179d67.jpg)
![Screenshot 2022-09-18 132929](https://user-images.githubusercontent.com/50377455/190899897-bc2a1ed9-054a-4a25-a184-c74e20ddf78d.jpg)

**Comment by Ashok0** [comment] 2022-09-23 21:58
I'm afraid I'm unable to reproduce this error.  Make sure your .NET Framework is up to date.  Closing this issue for now.

**Closed as completed by Ashok0** 2022-09-23 21:58 UTC

**Comment by trillex** [comment] 2023-04-11 18:23
Sorry for necroing, but in case other people find this topic. 

This is due to Windows blocking the file. You can go into properties for the zip file and set this 
![image](https://user-images.githubusercontent.com/6444691/231254835-8844276e-217d-4b07-9067-6d28ee34902e.png)

Or, you can do this: 

1.  start powershell
2.  cd to mo2 installation folder
3.  run `dir -Recurse | Unblock-File`

**Comment by Petronius29** [comment] 2024-12-02 11:09
>@trillex this helped with my issue even though you necroed, so thank you!
